### ISSUE TITLE
关于test_word.txt

### ISSUE THREAD

**Issue by Zbeeee** [SamaelChen/hexo-practice-code#1]
请问这个文件在哪里可以找到呢？

**Comment by SamaelChen** [comment]
https://github.com/stanfordnlp/GloVe

用的是glove 6b 100d这个文件

**Comment by Zbeeee** [comment]
就是txt版本的glove 6B 100d就可以吗？

**Comment by SamaelChen** [comment]
@Zbeeee 

需要用gensim转换一下格式，其实就是首行插入ntoken和ndim两个信息，代码就是下面这个，你改改文件路径就行。
```python
from gensim.test.utils import datapath, get_tmpfile
from gensim.models import KeyedVectors

glove_file = datapath('test_glove.txt')
tmp_file = get_tmpfile("test_word2vec.txt")
from gensim.scripts.glove2word2vec import glove2word2vec
glove2word2vec(glove_file, tmp_file)
model = KeyedVectors.load_word2vec_format(tmp_file)
```

**Comment by Zbeeee** [comment]
好的，谢谢大佬

**Comment by Zbeeee** [comment]
请问最后的输出为什么要将lstm的第一个输出和最后一个输出拼到一起呢？在经过双向的LSTM后，输出的hidden size以及变成了两倍，应该是已经包含了前后的信息吧。我在有的例子中看到是没有这个操作的，就是直接输出啊。

**Comment by SamaelChen** [comment]
@Zbeeee 是这样，双向的LSTM同时正向扫一遍，反向扫一遍。就像这个图
<img src='https://upload-images.jianshu.io/upload_images/1667471-ad054c3a8b703f28.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240'>
我取的第一个输出是正向的初始时刻和反向的最后一个时刻，最后一个输出是正向的最后一个时刻和反向的第一个时刻。这个要不要拼起来就是看自己怎么操作了，只用最后一个时刻也没什么问题。

**Comment by Zbeeee** [comment]
好的，感谢！
