### ISSUE TITLE
关于Topic2Essay_MAT_bleu-adaptive的attention

### ISSUE THREAD

**Issue by mlguy123** [SamaelChen/hexo-practice-code#2]
在官方的源码中，有一个gate的机制，全部初始为1，板主在这里用nn.Linear的attention的weight全部初始为1来代替了，请问这样与官方的版本不同的地方在哪里？还有就是，在predict_rnn_ada时，需要把attention的weight重新初始化嘛？

谢谢板主解答

**Comment by SamaelChen** [comment]
@mlguy123 没什么区别，官方的那个gate我自己简单看的时候就觉得是topics的权重。predict的时候不需要重新初始化，其实PyTorch的AdaptiveLogSoftmaxWithLoss其实就是个两层的神经网络，重新初始化就丢掉信息了。

**Comment by mlguy123** [comment]
@SamaelChen 可是他是根据topics出现的频繁程度来决定权重，这样为什么不需要每换一组topics的时候就再一次初始gate为1呢？这样不会连带影响嘛？

**Comment by SamaelChen** [comment]
>@SamaelChen 可是他是根据topics出现的频繁程度来决定权重，这样为什么不需要每换一组topics的时候就再一次初始gate为1呢？这样不会连带影响嘛？

@mlguy123 我的理解是，这样训练是得到一个基于该语境的全局权重。不过我自己在测试的时候发现，如果每一个batch把topics打乱，最后的weight就趋近于平均

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mlguy123** [comment]
@SamaelChen 以板主在最後的測試，topics為['小朋友', '学习', '英语', '分数', '<PAD>']，可是出來的結果與訓練過程中都是以「我的家乡在那里...」作為開頭。以板主的理解，是不是該解釋為，是這整個dataset的語境導致這樣的結果？

**Comment by mlguy123** [comment]
@SamaelChen 以板主在最后的测试，topics为['小朋友', '学习', '英语', '分数', '<PAD>']，可是出来的结果与训练过程中都是以「我的家乡在那里...」作为开头。以板主的理解，是不是该解释为，是这整个dataset的语境导致这样的结果？

**Comment by SamaelChen** [comment]
>@SamaelChen 以板主在最後的測試，topics為['小朋友', '学习', '英语', '分数', '<PAD>']，可是出來的結果與訓練過程中都是以「我的家乡在那里...」作為開頭。以板主的理解，是不是該解釋為，是這整個dataset的語境導致這樣的結果？

@mlguy123 是的，实际上我最后用的“小朋友”这几个topic是原来语料中没有学习过的。当时想试试会不会机器自己灵光一现变成奇奇怪怪的句子

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mlguy123** [comment]
@SamaelChen 那这样是不是跟官方论文的预期有所不同？原本的理想应该是会根据给定的topics来生成相应的文本，但按照这样的理解的话，整个dataset都必须是密切相关的topics？所以如果想用wikitext来训练的话，结果大概会是一团糟啰？毕竟每篇文章的主题相差很大

**Comment by SamaelChen** [comment]
@mlguy123 我觉得没有冲突呀，用Wikipedia的话会有更多更广泛的语境，这种情况下其实机器能学会的就更宽泛。我用的是散文的语料，机器肯定学不到那些家长里短的东西。如果要做一个任意topic都可以有输出的模型，我觉得需要的语料库是非常庞大的。

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mlguy123** [comment]
@SamaelChen 我看你用的语料库也不小阿，八万多则散文。敢问板主用什么GPU呢，我很想试试看

**Comment by SamaelChen** [comment]
@mlguy123 实际上不是八万篇散文，是八万段散文，一篇拆成好几段这样。我当时用的是两块1080ti，不过数据量不大，单卡效率更高

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jwc19890114** [comment]
原来是2块1080ti，难怪我用2070S感觉够呛啊。。。
