### ISSUE TITLE
关于注意力机制的问题

### ISSUE THREAD

**Issue by jwc19890114** [SamaelChen/hexo-practice-code#5]
您好，看了您文本生成的三个notebook，其中TAT和MAT模型都使用到了attention机制，但是我再抄代码的时候发现您在TAT模型中使用的attention和之前我看到的不太一样。好像您在self.attn中用的是一个Linear层来对5个topic做处理，之后在forward方法中对5个topic的状态进行处理（这部分看的不是太明白）。
我想知道您这么写的依据是什么呢，另外能否推荐attention比较基础的实现代码么，我在网上找的好像讲解的都不是很清晰。
谢谢。

**Comment by SamaelChen** [comment]
呃，这里实在不好意思，这里代码有问题，不是正确的attention机制写法。我近期会更新一篇attention机制的博客，尽可能体系化梳理一下Attention机制，后面这部分的问题我会修复掉。Attention机制的话基础可以去看一下pytorch官方教程里面有一篇Attention的，写的很详细。
https://pytorch.org/tutorials/intermediate/seq2seq_translation_tutorial.html
