### ISSUE TITLE
How to generate 128x128 images?

### ISSUE THREAD

**Issue by Weile0409** [SamaelChen/hexo-practice-code#7]
Hi, I would like to ask you how to generate 128x128 images through the trained Generator , I use your code to train, I generate the images successfully but the images' size are 4x4

Looking forward to your reply， thank you !

**Comment by SamaelChen** [comment]
If you wanna generate images from the trained generator net, you should set the argument "expand" to 5. The code looks like netG(fixed_noise, expand, alpha)

**Comment by Weile0409** [comment]
oh I see, than you very much and sorry to bother you !
