### ISSUE TITLE
test_word.txt

### ISSUE THREAD

**Issue by syfan7561** [SamaelChen/hexo-practice-code#8]

**Comment by SamaelChen** [comment]
https://github.com/stanfordnlp/GloVe
I used glove 6b 100d.

You can modify the code below:

from gensim.test.utils import datapath, get_tmpfile
from gensim.models import KeyedVectors

glove_file = datapath('test_glove.txt')
tmp_file = get_tmpfile("test_word2vec.txt")
from gensim.scripts.glove2word2vec import glove2word2vec
glove2word2vec(glove_file, tmp_file)
model = KeyedVectors.load_word2vec_format(tmp_file)

**Comment by syfan7561** [comment]
Okay,thank you very much for your reply.
